### ISSUE TITLE
Problem: when starting gcode while not calibrated, WebUI disconnects 

### ISSUE THREAD

**Issue by JustusRijke** [BarbourSmith/FluidNC#180]
### Controller Board

Maslow 4.0

### Machine Description

Maslow 4.0

### Configuration file

```yaml
board: Maslow
name: Maslow S3 Board
meta: 
Maslow_vertical: false
Maslow_calibration_grid_width_mm_X: 1500.000000
Maslow_calibration_grid_height_mm_Y: 800.000000
Maslow_calibration_grid_size: 7
Maslow_tlX: -3.500000
Maslow_tlY: 3516.500000
Maslow_trX: 4190.600098
Maslow_trY: 3510.300049
Maslow_blX: 0.000000
Maslow_blY: 0.000000
Maslow_brX: 4194.500000
Maslow_brY: 0.000000
Maslow_tlZ: 100.000000
Maslow_trZ: 56.000000
Maslow_blZ: 34.000000
Maslow_brZ: 78.000000
Maslow_Retract_Current_Threshold: 1300
Maslow_Calibration_Current_Threshold: 1200
Maslow_Acceptable_Calibration_Threshold: 0.450000
Maslow_beltEndExtension: 30.000000
Maslow_armLength: 123.400002
stepping: 
  engine: Timed
  idle_ms: 240
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12

uart1: 
  txd_pin: gpio.1
  rxd_pin: gpio.2
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

spi: 
  miso_pin: gpio.13
  mosi_pin: gpio.11
  sck_pin: gpio.12

sdcard: 
  cs_pin: gpio.10
  card_detect_pin: NO_PIN
  frequency_hz: 8000000

kinematics: 
  Cartesian: 

axes: 
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  x: 
    steps_per_mm: 80.000000
    max_rate_mm_per_min: 2000.000000
    acceleration_mm_per_sec2: 25.000000
    max_travel_mm: 2438.399902
    soft_limits: false
    homing: 
      cycle: -1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000000
      null_motor: 

  y: 
    steps_per_mm: 80.000000
    max_rate_mm_per_min: 2000.000000
    acceleration_mm_per_sec2: 25.000000
    max_travel_mm: 1219.199951
    soft_limits: false
    homing: 
      cycle: -1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000000
      null_motor: 

  z: 
    steps_per_mm: 100.000000
    max_rate_mm_per_min: 400.000000
    acceleration_mm_per_sec2: 10.000000
    max_travel_mm: 100.000000
    soft_limits: false
    homing: 
      cycle: -1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000000
      feed_mm_per_min: 50.000000
      seek_mm_per_min: 200.000000
      settle_ms: 250
      seek_scaler: 1.100000
      feed_scaler: 1.100000

    motor0: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000000
      tmc_2209: 
        uart_num: 1
        step_pin: gpio.15
        direction_pin: gpio.16
        disable_pin: NO_PIN
        r_sense_ohms: 0.110000
        run_amps: 1.000000
        hold_amps: 0.500000
        microsteps: 1
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: true
        addr: 0
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3

    motor1: 
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1.000000
      tmc_2209: 
        uart_num: 1
        step_pin: gpio.46
        direction_pin: gpio.38
        disable_pin: NO_PIN
        r_sense_ohms: 0.110000
        run_amps: 1.000000
        hold_amps: 0.500000
        microsteps: 1
        toff_disable: 0
        toff_stealthchop: 5
        use_enable: true
        addr: 1
        run_mode: StealthChop
        homing_mode: StealthChop
        stallguard: 0
        stallguard_debug: false
        toff_coolstep: 3

control: 
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant: 
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe: 
  pin: NO_PIN
  check_mode_start: true

macros: 
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start: 
  must_home: true
  deactivate_parking: false
  check_limits: false

parking: 
  enable: false
  axis: Z
  target_mpos_mm: -5.000000
  rate_mm_per_min: 800.000000
  pullout_distance_mm: 5.000000
  pullout_rate_mm_per_min: 250.000000

user_outputs: 
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN

NoSpindle: 

arc_tolerance_mm: 0.002000
junction_deviation_mm: 0.010000
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
```

### Startup Messages

```text
[MSG:INFO: FluidNC v0.87 (Maslow-Main-ec171155-dirty)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:maslow.yaml]
[MSG:INFO: Machine Maslow S3 Board]
[MSG:INFO: Board Maslow]
[MSG:INFO: UART1 Tx:gpio.1 Rx:gpio.2 RTS:NO_PIN Baud:115200]
[MSG:INFO: SPI SCK:gpio.12 MOSI:gpio.11 MISO:gpio.13]
[MSG:INFO: SD Card cs_pin:gpio.10 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:Timed Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:240ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-2438.400,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1219.200,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-100.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:0 Step:gpio.15 Dir:gpio.16 Disable:NO_PIN R:0.110]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_2209 UART1 Addr:1 Step:gpio.46 Dir:gpio.38 Disable:NO_PIN R:0.110]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: Z2 Axis driver test passed]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:FritzTheCat]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.178.33]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://maslow.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 0 [FluidNC v0.87 (Maslow-Main-ec171155-dirty) (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: Encoder connected on Top Left]
[MSG:INFO: Motor detected on Top Left]
[MSG:INFO: Encoder connected on Top Right]
[MSG:INFO: Motor detected on Top Right]
[MSG:INFO: Encoder connected on Bottom Left]
[MSG:INFO: Motor detected on Bottom Left]
[MSG:INFO: Encoder connected on Bottom Right]
[MSG:INFO: Motor detected on Bottom Right]
[MSG:INFO: Current z-axis position loaded as: 0.000]
[MSG:INFO: Starting Maslow Version 0.87]
[MSG:INFO: Channel auto report interval set to 50 ms]
MINFO: { "homed": false,"calibrationInProgress": false,"tl": 0.000,"tr": 0.000,"br": 0.000,"bl": 0.000,"etl": 0.000,"etr": 0.000,"ebr": 0.000,"ebl": 0.000,"extended": false}
[MSG:INFO: Caution: Unlocked]
[MSG:INFO: Tool No: 0]
[MSG:INFO: Using spindle NoSpindle]
[MSG:WARN: Position error on Bottom Right axis exceeded 15mm while running. Error is -2588.925mm Counter: 1]
[MSG:WARN:[MSG:WARN: Position error on Top Right axis exceeded 15mm while running. Error is -2577.947mm Counter: 1]
[MSG:
[MSG:WARN: Positiunning. Error is -2582.651mm Counter: 1]
[MSG:WARN: Previous error was -2582.651mm]
[MSG:WARN: Position error on Bottom Left axis exceeded 15mm while running. Error is -2583.604mm Counter: 1]
[MSG:WARN: Previous error was -2583.604mm]
[MSG:WARN: Position error on Bottom Right axis exceeded 15mm while running. Error is -2588[MSG:WARN: Previous error was -2588.925mm]
[MSG:WARN: Position error on Top Right axis exceeded 15mm while running. Error is -2577.947mm Counter: 2]
[MSG:WARN: Previous error was -2577.947mm]
[MSG:WARN: Position error on Topunning. Error is -2582.651mm Counter: 2]
[MSG:WARN: Previous error was -2582.651mm]
[MSG:WARN: Position error on Bottom Left axis exceeded 15mm while running. Error is -2583.604mm Counter: 2]
[MSG:WARN: Previous error was -2583.604mm]
[MSG:WARN: Position error on Bottom Right axis exceeded 15mm while running. Error is -2588.925mm Counter: 3]
Resetting MCU
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4214812a
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
E (362) esp_core_dump_flash: No core dump partition found!
E (362) esp_core_dump_flash: No core dump partition found!

[MSG:INFO: FluidNC v0.87 (Maslow-Main-ec171155-dirty)]
[MSG:INFO: Compiled with ESP32 SDK:v4.4.7-dirty]
[MSG:INFO: Local filesystem type is littlefs]
[MSG:INFO: Configuration file:maslow.yaml]
[MSG:INFO: Machine Maslow S3 Board]
[MSG:INFO: Board Maslow]
[MSG:INFO: UART1 Tx:gpio.1 Rx:gpio.2 RTS:NO_PIN Baud:115200]
[MSG:INFO: SPI SCK:gpio.12 MOSI:gpio.11 MISO:gpio.13]
[MSG:INFO: SD Card cs_pin:gpio.10 detect:NO_PIN freq:8000000]
[MSG:INFO: Stepping:Timed Pulse:4us Dsbl Delay:0us Dir Delay:0us Idle Delay:240ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Axis X (-2438.400,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Y (-1219.200,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO: Axis Z (-100.000,0.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     tmc_2209 UART1 Addr:0 Step:gpio.15 Dir:gpio.16 Disable:NO_PIN R:0.110]
[MSG:INFO:   Motor1]
[MSG:INFO:     tmc_2209 UART1 Addr:1 Step:gpio.46 Dir:gpio.38 Disable:NO_PIN R:0.110]
[MSG:INFO: Z Axis driver test passed]
[MSG:INFO: Z2 Axis driver test passed]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Using spindle NoSpindle]
[MSG:INFO: Connecting to STA SSID:FritzTheCat]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connecting...]
[MSG:INFO: Connected - IP is 192.168.178.33]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://maslow.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 0 [FluidNC v0.87 (Maslow-Main-ec171155-dirty) (wifi) '$' for help]
[MSG:INFO: '$H'|'$X' to unlock]
[MSG:INFO: Encoder connected on Top Left]
[MSG:INFO: Motor detected on Top Left]
[MSG:INFO: Encoder connected on Top Right]
[MSG:INFO: Motor detected on Top Right]
[MSG:INFO: Encoder connected on Bottom Left]
[MSG:INFO: Motor detected on Bottom Left]
[MSG:INFO: Encoder connected on Bottom Right]
[MSG:INFO: Motor detected on Bottom Right]
[MSG:INFO: Current z-axis position loaded as: 0.000]
[MSG:INFO: Starting Maslow Version 0.87]
[MSG:INFO: Channel auto report interval set to 50 ms]
MIN"tr": -0.011,"br": 0.000,"bl": 0.000,"etl": 0.000,"etr": -0.011,"ebr": 0.000,"ebl": 0.000,"extended": false}
```

### What happened?

Steps to reproduce:
- turn on Maslow
- connect to WebUI
- upload Maslow logo gcode file
- click "Play" 

Fan starts to run, shortly after WebUI disconnects and cannot be reached. Device still connected to network. Also still responsive when using fluidterm. Powercycle needed to reset.
